FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Comercio de Eletrônicos

Uma API para comercio de venda de eletronicos.

## Produtos eletrônicos [/produtos]
Tem como finalidade realizar o CRUD de produtos disponiveis em uma comercio de eletrônicos.

### Listar produtos [GET]

+ Response 200 (application/json)

        [
            {
                "id": 0001,
                "tipo": "Notebook",
                "preço": "2599,00",
            },
            {
                "id": 0002,
                "tipo": "Desktop",
                "preço": "2400,00",
            },
            {
                "id": 0003,
                "tipo": "Desktop",
                "preço": "6999,00",
            },
            {
                "id": 0004,
                "tipo": "Notebook",
                "preço": "7985,00",
            }
        ]

### Cadastrar produtos [POST]

+ Request (application/json)

        {
            "tipo" : "Notebook",
            "preço": "8998,00"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "id": 0005,
                "tipo": "Notebook",
                "preço": "25999,00",
            },
            {
                "id": 0006,
                "tipo": "Desktop",
                "preço": "46999,00",
            }
            
### Atualizar produtos [PUT /produtos/{id}]

+ Request (application/json)

        {
            "tipo" : "Notebook",
            "preço": "8998,00"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "id": 0005,
                "tipo": "Notebook",
                "preço": "25999,00",
            },
            {
                "id": 0006,
                "tipo": "Desktop",
                "preço": "46999,00",
            }

### Buscar produtos [GET /produtos/{id}]

+ Response 200 (application/json)

        [
            {
                "id": 0001,
                "tipo": "Notebook",
                "preço": "2599,00",
            }
        ]
        
### Deletar produtos [DELETE /produtos/{id}]

+ Response 200 (application/json)

    + Body

            [
                {
                    "id": 0001,
                    "tipo": "Notebook",
                    "preço": "2599,00",
                }
            ]